package net.scottnotfound.clara.interpret;

public enum TokenType {


    PAREN_LEFT, PAREN_RIGHT,
    BRACE_LEFT, BRACE_RIGHT,
    BRACKSQ_LEFT, BRACKSQ_RIGHT,
    BRACKNQ_LEFT, BRACKNQ_RIGHT,

    COMMA, DOT, MINUS, PLUS,
    SEMICOLON, TICK, ASTERISK,
    COLON, EXCLAMK, QUESTIONMK,
    QUOTEMK_S, QUOTEMK_D, PIPE,
    SLASH_BACK, SLASH_FRWD,
    ATSIGN, AMPERSAND, OCTOTHORPE,
    TILDE, UNDERSCORE, CARET,
    PERCENT, CURRENCY_USD,

    NOT_EQUALS, LESS_EQUALS,
    GREATER_EQUALS, EQUALS,

    STRING, NUMBER, IDENTIFIER,

    EOF





}
